#159987361 Register a user
andela/metis-ah-frontend pull request #16
Opened 2018-10-12 11:17 UTC by DanielAdek

#### What does this PR do?
Register a user
#### Description of Task to be completed?
* create sign up form
* Install axios
* get toastr cdn (https://codeseven.github.io/toastr/)
* create validation functionality

#### How should this be manually tested?
1. Clone repository
2. On your terminal run this command git checkout ft-signup-159987361
3. run npm install to install packages
5. run npm  run dev to start app

#### What are the relevant pivotal tracker stories?
#159987361

2018-10-15 13:06 UTC, iAmao requested changes

2018-10-15 13:06 UTC, iAmao commented on src/components/HOC/Aux.js
> +const aux = props => props.children;
This isn't a higher order component. 
Please check out this documentation(https://reactjs.org/docs/higher-order-components.html)on it and try to play around with it on https://codesandbox.io

2018-10-15 13:06 UTC, iAmao commented on src/components/atoms/Avatar/index.js
> +import './style.scss';
Let's import this after all other imports.

2018-10-15 13:06 UTC, iAmao commented on src/components/atoms/Avatar/index.js
> +const avatar = () => (
Let's try and make this more reusable.

We can re-write as
```
const Avatar = (props) => (
  <img {...props} alt="avatar" />
)

Avatar.propTypes = {
  className: PropTypes.string.isRequired,
  src: PropTypes.string.isRequired
}

Avatar.defaultProps = {
  className: 'avatar'
}
```

2018-10-15 13:06 UTC, iAmao commented on src/components/atoms/Avatar/index.js
> +const avatar = () => (
Let's make the className atom__avatar

2018-10-15 13:06 UTC, iAmao commented on src/components/atoms/Button/Button.js
> +const button = props => (
Remove eslint disable and let's destructure like this:
```
const Button = ({ children, ...props }) => {
 return (
  <button {...props}>
     {children}
  </button>
  );
}
```

2018-10-15 13:06 UTC, iAmao commented on src/components/atoms/Button/Media/MediaButtons.js
> +import './MediaButtons.scss';
Move stylesheet down

2018-10-15 13:06 UTC, iAmao commented on src/components/atoms/Button/Media/MediaButtons.js
> +  <Aux>
This isn't how a HOC is used please refer to earlier docs for this. Its tricky at first but worth it

2018-10-15 13:06 UTC, iAmao commented on src/components/atoms/Button/Media/MediaButtons.js
> +      <Button class="button is-medium GoogleBtn">
Please refrain from naming a prop `class` or any JS `keyword` syntax

2018-10-15 13:06 UTC, iAmao commented on src/components/atoms/Modal/Modal.js
> +/* eslint-disable */
same here

2018-10-15 13:06 UTC, iAmao commented on src/components/compounds/Hero/index.js
>  import './style.scss';
Lets move this down

2018-10-15 13:06 UTC, iAmao commented on src/components/compounds/Hero/index.js
> +          (modalOpen) && (
We don't need the `(`

2018-10-15 13:06 UTC, iAmao commented on src/components/compounds/Hero/index.js
> +            <Modal clicked={this.closeModalHandler}>
Lets just use `onClick` for the prop name

2018-10-15 13:06 UTC, iAmao commented on src/components/compounds/Signup/Signup.js
> +    this.setState({ newUser: { ...newUser, [event.target.name]: event.target.value } });
This line looks too long

2018-10-15 13:06 UTC, iAmao commented on src/components/compounds/Signup/Signup.js
> +  showPassword = (e) => {
Think we can re-write this as
```
showPassword =  () => {
  return this.setState({ showPassword: !this.state.showPassword });
}
```

2018-10-15 13:06 UTC, iAmao commented on src/components/compounds/Signup/Signup.js
> +                      <Input
This can be re-written as :
```
<Input
                        type={this.state.showPassword ? 'text' : 'password'}
                        name="confirmPassword"
                        onChange={this.handleChangeEvent}
                        value={newUser.confirmPassword}
                        className="input is-medium"
                      />
```

2018-10-15 13:06 UTC, iAmao commented on src/components/compounds/Signup/Signup.js
> +    passwordType: 'password'
replace `passwordType : 'password'` with `showPassword: false`

2018-10-15 13:06 UTC, iAmao commented on src/components/compounds/Signup/Signup.js
> +                        <button type="button" onClick={e => this.showPassword(e)} className="ShowPassword">show password</button>
`onClick={this.showPassword}`

2018-10-15 13:06 UTC, iAmao commented on src/components/compounds/Signup/Signup.js
> +                        type={passwordType}
Same as below comment

2018-10-15 13:06 UTC, iAmao commented on src/components/compounds/Signup/Signup.js
> +    createUserAction: (userData) => dispatch(createUser(userData))
This is more than 2 spaces

2018-10-15 13:06 UTC, iAmao commented on src/store/actions/authUser.js
> +      const allErrors = error.response.data.data.messages
Think we'll need to refactor the signup endpoint for this. Try and make it so that only one format of error is returned.

2018-10-15 13:06 UTC, iAmao commented on src/util/helpers/formValid.js
> +  if (!val.match(/\S+@\S+\.\S+/)) {
Let's try and use the regex test method.

2018-10-15 13:06 UTC, iAmao commented on src/util/helpers/formValid.js
> +  if (!userDetails.password) {
Let's check the password length before sending request to the backend

2018-10-15 13:06 UTC, iAmao commented on tests/landingPage.spec.js
> +      const wrapper = mount(<Provider store={store}><Hero /></Provider>);
Lets create a mock store for this off our main store

2018-10-15 13:06 UTC, iAmao commented on tests/signup.spec.js
> +  describe('render()', () => {
describe text shouldn't be a function

2018-10-15 13:06 UTC, iAmao commented on tests/signup.spec.js
> +  describe('render()', () => {
Also, test that clicking and all interactions work. This will require making use of an interceptor like `moxios`

2018-10-17 07:53 UTC, DanielAdek commented
Thanks for the feedback 👍 iAmao.
I have incorporated all the feedback.

2018-10-17 10:56 UTC, johngorithm commented on src/store/constants/index.js
>  // eslint-disable-next-line
Good Job Dan,
However, this (`// eslint-disable-next-line`) is not required as the code below did not violate the project's coding standards. Please let's remove it and other similar cases

2018-10-17 11:56 UTC, iAmao requested changes

2018-10-17 11:56 UTC, iAmao commented on src/components/atoms/Button/Media/index.js
> +const mediaButtonSection = () => (
Let's make this Pascal case

2018-10-17 11:56 UTC, iAmao commented on src/components/atoms/Button/Media/style.scss
> +    .Container {
Lets make this lower cased

2018-10-17 11:56 UTC, iAmao commented on src/components/atoms/Button/Media/index.js
> +    <div className="Container">
Lets make this lower case

2018-10-17 11:56 UTC, iAmao commented on src/components/compounds/Hero/index.js
> +  state={
lets leave a space before and after `=`

2018-10-17 11:56 UTC, iAmao commented on src/components/compounds/Hero/index.js
> +  showModalHandler = () => {
Why do we need this? IMO I don't think this is necessary

2018-10-17 11:56 UTC, iAmao commented on src/components/compounds/Hero/index.js
> +          : <Button text="GET STARTED" onClick={this.showModalHandler} />
We can re-write this like,
```suggestion
          : <Button text="GET STARTED" onClick={this.props.showModalHandler} />
```

2018-10-17 11:56 UTC, iAmao commented on src/components/compounds/ProfileNav/index.js
> +      { !isAuth && <LoginButton />}
Lets remove the ` ` after `{`

2018-10-17 11:56 UTC, iAmao commented on src/components/compounds/Signup/Signup.js
> +    /*eslint-disable*/
remove the disable. Slack me the error

2018-10-17 11:56 UTC, iAmao commented on src/components/compounds/Signup/Signup.js
> +
remove extra line

2018-10-17 11:56 UTC, iAmao commented on src/index.js
> +
remove extra line

2018-10-17 11:56 UTC, iAmao commented on src/index.js
> +axios.defaults.baseURL = 'https://metis-ah-staging.herokuapp.com/api/v1';
can we move this to a config file or env variable?

2018-10-17 11:56 UTC, iAmao commented on src/static/index.html
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
Lets preload these stylesheets

2018-10-18 10:39 UTC, iAmao commented
Nice, a couple of issues though:
- Username is not unique.
- Password error does not show on alert.
- User's session is not persisted.

2018-10-19 11:10 UTC, merged