#161050749 user can view list of articles
andela/metis-ah-frontend pull request #18
Opened 2018-10-12 11:47 UTC by tomiadebanjo

2018-10-17 12:18 UTC, iAmao requested changes

2018-10-17 12:18 UTC, iAmao commented on src/components/compounds/ArticleContainer/index.js
> +  componentWillReceiveProps(nextProps) {
This will soon be deprecated. let's use `getDerivedStateFromProps` instead

2018-10-17 12:18 UTC, iAmao commented on src/components/compounds/ArticleContainer/index.js
> +    const	{	articles,	loading	}	=	this.props;
Fix spacing on this line

2018-10-17 12:18 UTC, iAmao commented on src/components/compounds/CategoriesNav/index.js
> +const MinorNav = () => (
Name component same as file name

2018-10-17 12:18 UTC, iAmao commented on src/components/compounds/ArticleContainer/index.js
> +      getArticles(category);
Let's move this to `getDerivedStateFromProps`

2018-10-17 12:18 UTC, iAmao commented on src/components/compounds/ArticleContainer/index.js
> +      console.log(article);
remove console log

2018-10-17 12:18 UTC, iAmao commented on src/components/compounds/ArticleContainer/index.js
> +					&& (
excess spaces

2018-10-17 12:18 UTC, iAmao commented on src/components/compounds/FooterBrand/index.js
> +const Brand = () => (
File should be in Pascal case

2018-10-17 12:18 UTC, iAmao commented on src/components/compounds/FooterBrand/index.js
> +const Brand = () => (
Name component same as file name

2018-10-17 12:18 UTC, iAmao commented on src/components/compounds/Hero/index.js
> +  console.log(buttonIsVisible);
remove console.log

2018-10-17 12:18 UTC, iAmao commented on src/components/compounds/Hero/index.js
> +export default connect(mapStateToProps)(Radium(Hero));
You are exporting before setting propTypes here

2018-10-17 12:18 UTC, iAmao commented on src/components/compounds/Hero/index.js
> +
Let's remove extra line

2018-10-17 12:18 UTC, iAmao commented on src/pages/Landing/index.js
> +
Let's remove extra line

2018-10-17 12:18 UTC, iAmao commented on src/store/actions/article.js
> +      console.log(error.response);
remove console log

2018-10-17 12:18 UTC, iAmao commented on src/store/actions/article.js
> +  axios
let's return this

2018-10-17 12:18 UTC, iAmao commented on tests/landingPage.spec.js
> +      // const wrapper = mount(<Hero />);
remove commented line

2018-10-18 09:25 UTC, johngorithm commented
Good Job Tomi.

However, I noticed from the above 2 images that `Home` nav remains **active** despite the fact the categories in focus are `Fashion` and `Mathematics`. I think it will better if the `clicked` category bears the `active` state

2018-10-26 11:06 UTC, iAmao approved these changes

2018-10-26 11:07 UTC, merged