#161807971 create a comprehensive readme documentation
andela/metis-ah-frontend pull request #41
Opened 2018-11-08 16:20 UTC by johngorithm

#### What does this PR do?
create a comprehensive readme documentation

#### Tasks needed to be completed
- update readme file with info about the project

#### Pivotal Tracker ID associated with this story
161807971

#### Screenshots
![screen shot 2018-11-08 at 5 18 19 pm](https://user-images.githubusercontent.com/30831276/48211723-62543080-e37a-11e8-8cbd-44823b619676.png)

2018-11-08 19:03 UTC, joeeasy requested changes
Good job John, just fix the tiny changes 👍🏻

2018-11-08 19:03 UTC, joeeasy commented on README.md
> +* The **develop** branch automatically deploys whenever ever a pull request is merged.
Nice job on the readme,  however, you mistakenly added `ever` to after `whenever`

2018-11-08 19:03 UTC, joeeasy commented on README.md
> +https://metis-ah-frontend.herokuapp.com/
Well done for providing the link to viewing the application, you could also use a markdown like this ```[View live app Here](https://metis-ah-frontend.herokuapp.com/)``` [View live app Here](https://metis-ah-frontend.herokuapp.com/)

2018-11-09 08:53 UTC, johngorithm commented on README.md
> +* The **develop** branch automatically deploys whenever ever a pull request is merged.
Alright.
Thanks for the observation

2018-11-09 08:54 UTC, emmaadesile requested changes

2018-11-09 08:54 UTC, emmaadesile commented on README.md
> +This project creates a platform for Authors to create and share articles. It is equally a platform that allows user to read articles, react to them and socialize with one another.
Good job on the readme. Please check the last part of line 14, user should be users

2018-11-09 08:55 UTC, johngorithm commented on README.md
> +This project creates a platform for Authors to create and share articles. It is equally a platform that allows user to read articles, react to them and socialize with one another.
Thanks.
I will sure look into that

2018-11-09 10:11 UTC, emmaadesile approved these changes

2018-11-09 10:16 UTC, joeeasy approved these changes

2018-11-09 11:28 UTC, merged