#161748169 toggle category navigation 
andela/metis-ah-frontend pull request #43
Opened 2018-11-09 13:43 UTC by joeeasy

#### What does this PR do?
Toggle category navigation bar 

#### Description of tasks to be completed
- add hamburger icon to category nav on a smaller device
- toggle category nav items on a smaller device 

#### Relevant Pivotal tracker stories
#161748169

2018-11-09 16:11 UTC, johngorithm commented
Good Job @joeeasy 
However, while checking out your fix on its review app, I noticed that at some point, the **x** icon displays instead of the **hamburger** icon when the `dropdown` is not **active**. Of course, this can be misleading and I suggest you put your technical skills together and get it fixed. 👍 

![screen shot 2018-11-09 at 4 48 13 pm](https://user-images.githubusercontent.com/30831276/48272884-f4723c80-e43f-11e8-8cbc-006efc55bd75.png)

2018-11-09 16:13 UTC, johngorithm requested changes
👍 

Please handle the requested change

2018-11-09 16:17 UTC, emmaadesile requested changes
Great job on making the categories responsive. I observed that the hamburger menu was not responding as it should. Kindly fix it.

2018-11-09 16:17 UTC, emmaadesile commented on src/components/compounds/CategoriesNav/style.scss
> +}
Add a new line here

2018-11-09 17:14 UTC, emmaadesile approved these changes
LGTM

2018-11-12 08:47 UTC, johngorithm approved these changes

2018-11-13 12:18 UTC, merged