Ch setup redux 159987355
andela/metis-ah-frontend pull request #7
Opened 2018-10-03 18:50 UTC by DanielAdek

#### What does this PR do?
Setup redux.
#### Description of Task to be completed?
* install redux
* install react-redux
* install redux-thunk
* create store folder
create `index.js` file in store folder
* create constants folder
create `index.js` file constants folder
* create reducers folder
create `index.js` file reducers folder

#### How should this be manually tested?
1. Clone repository
2. On your terminal run this command git checkout `ch-setup-redux-159987355`
3. run npm install to install packages
4. create a simple react app and manage states with redux

#### Any background context you want to provide?
This branch basically setup redux in your project. To run a redux application on this branch, you need to create a simple redux app. learn redux here https://redux.js.org/
If you are using chrome, please install the redux chrome extension https://chrome.google.com/webstore/search/redux

#### What are the relevant pivotal tracker stories?
[#159987355](https://www.pivotaltracker.com/story/show/159987355)

2018-10-04 12:34 UTC, iAmao requested changes

2018-10-04 12:34 UTC, iAmao commented on src/app.js
> +// import 'babel-polyfill';
I don't think we need this

2018-10-04 14:35 UTC, DanielAdek commented on src/app.js
> +// import 'babel-polyfill';
I have removed it

2018-10-05 10:50 UTC, iAmao approved these changes

2018-10-05 10:50 UTC, merged